export class TestPopOverConstants {
	public static readonly STRING = {
		AW_POPOVER: 'aw-popover',
		AW_CONTENT: 'aw-popover__content',
		HEADER_CONTAINER: 'aw-popover__header-container',
		HEADER: 'aw-popover__header',
		CLOSE_BUTTON: 'aw-popover__close-button',
		DELETE_ICON: 'delete-small',
		PATH: 'path',
		CLASSNAME: 'className',
		MOUSEDOWN: 'mousedown',
		CLICK: 'click',
		MOUSEOVER: 'mouseover',
		MOUSEOUT: 'mouseout',
		RESIZE: 'resize',
		DATA_POINT: 'aw-popover__datapoint',
		DATA_POINT_CONTENT: 'aw-popover__content__datapoint',
		CONTAINER: 'aw-popover__container',
		DATA_POINT_CONTAINER: 'aw-popover__container__data-point',
		TARGET: 'target',
		CONTENT: 'content',
		CLOSE_ICON: 'delete-small',
		TAGNAME: 'tagName',
		SCROLL: 'scroll',
		DATA_POINT_CLASS: '__data-point',
	};
}
