export class TestModalConstants {
	public static readonly STRING = {
		TEST_MODAL: 'test-modal',
		CONTAINER: 'test-modal__container',
		CONTAINER_LARGE: 'test-modal__container--large',
		HEADER: 'test-modal__header',
		HEADER_LARGE: 'test-modal__header--large',
		WRAPPER: 'test-modal__wrapper',
		CONTENT: 'test-modal__content',
		CONTENT_LARGE: 'test-modal__content--large',
		CONTENT_GREY: 'test-modal__content--grey',
		CONTAINER_INFORMATION: 'test-modal__container--information',
		CONTAINER_ACTION: 'test-modal__container--action',
		BUTTONS: 'test-modal__buttons',
		PRIMARY_BUTTON_PADDING: 'test-modal__primary-button--padding',
		CONTENT_HIDE: 'test-modal__content--hide',
		CONTENT_SHOW: 'test-modal__content--show',
		FOOTER: 'test-modal__footer',
		LARGE_FOOTER: 'test-modal__footer--large',
		FOOTER_WITH_LINK: 'test-modal__footer--with-link',
		MOUSEDOWN: 'mousedown',
		KEYDOWN: 'keydown',
		PATH: 'path',
		CLASSNAME: 'className',
		ACTION: 'action',
		INFORMATION: 'information',
	};
}
